include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    parameter_assignments: error
    public_member_api_docs: info
    avoid_print: warning
    todo: warning

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - lib/**/*.gr.dart
    - lib/**/*.iconfig.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

linter:
  rules:
    parameter_assignments: true

    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Good packages document everything
    public_member_api_docs: false

    # Back to the 80s
    lines_longer_than_80_chars: false

    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true